### ISSUE TITLE
ERR_MODULE_NOT_FOUND after 1.0.5 update

### ISSUE THREAD

**Issue by arek-widelab** [percy/cli#867]
## The problem

Hey,

After upgrade to version 1.0.5 from 1.0.0-beta.76 and executing by $ percy storybook ./storybook-build
I have an issue like:
[percy] Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/artystakodu/Desktop/widelab/fds/node_modules/@percy/storybook/dist/hooks/init' imported from /Users/artystakodu/Desktop/widelab/fds/node_modules/@percy/cli/dist/commands.js
Did you mean to import /Users/artystakodu/Desktop/widelab/fds/node_modules/@percy/storybook/dist/hooks/init.js?

## Environment

- Node version: 16.14.0
- `@percy/cli` version: 1.0.5
- Version of Percy SDK you’re using: "@percy/storybook": "^4.1.0",
- If needed, a build or snapshot ID:
- OS version: MacOS 12.2.1
- Type of shell command-line [interface]: bash

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Debug logs

Can't provide logs, same error appears.

**Comment by Robdel12** [comment]
Hey @arek-widelab! I'd track this issue: https://github.com/percy/percy-storybook/issues/533 We're going to be releasing an update either later today or early tomorrow (🤞🏼)
